access==1.1.9
affine @ file:///home/conda/feedstock_root/build_artifacts/affine_1674245120525/work
aiofiles @ file:///croot/aiofiles_1683773582346/work
aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1666878620108/work
aiohttp-client-cache @ file:///home/conda/feedstock_root/build_artifacts/aiohttp-client-cache_1689480802839/work
aioredis @ file:///home/conda/feedstock_root/build_artifacts/aioredis_1640650569180/work
aiosignal @ file:///home/conda/feedstock_root/build_artifacts/aiosignal_1667935791922/work
aiosqlite @ file:///home/conda/feedstock_root/build_artifacts/aiosqlite_1671461885930/work
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1666191106763/work/dist
appdirs @ file:///home/conda/feedstock_root/build_artifacts/appdirs_1603108395799/work
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1640817743617/work
argon2-cffi-bindings @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi-bindings_1666850859330/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
async-retriever @ file:///home/conda/feedstock_root/build_artifacts/async-retriever_1683503662829/work
async-timeout @ file:///home/conda/feedstock_root/build_artifacts/async-timeout_1640026696943/work
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1671632566681/work
aws-requests-auth==0.4.3
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1667688356751/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
beautifulsoup4 @ file:///croot/beautifulsoup4-split_1681493039619/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1656355450470/work
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1660586590972/work
boto3==1.26.115
botocore==1.29.115
Bottleneck @ file:///opt/conda/conda-bld/bottleneck_1657175564434/work
branca @ file:///home/conda/feedstock_root/build_artifacts/branca_1667848736831/work
brotlipy @ file:///home/conda/feedstock_root/build_artifacts/brotlipy_1666764672617/work
cattrs @ file:///home/conda/feedstock_root/build_artifacts/cattrs_1664824901782/work
certifi @ file:///croot/certifi_1690232220950/work/certifi
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1671179360775/work
cftime @ file:///home/conda/feedstock_root/build_artifacts/cftime_1666833828858/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1661170624537/work
click @ file:///home/conda/feedstock_root/build_artifacts/click_1666798198223/work
click-plugins==1.1.1
cligj @ file:///home/conda/feedstock_root/build_artifacts/cligj_1633637764473/work
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1674202310934/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
colorcet @ file:///home/conda/feedstock_root/build_artifacts/colorcet_1664843244467/work
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1670575068857/work
contextily @ file:///home/conda/feedstock_root/build_artifacts/contextily_1675710006446/work
contourpy @ file:///home/conda/feedstock_root/build_artifacts/contourpy_1673633659350/work
cryptography @ file:///croot/cryptography_1689373676338/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
cytoolz @ file:///home/conda/feedstock_root/build_artifacts/cytoolz_1666829688252/work
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1673644363191/work
debugpy @ file:///croot/debugpy_1690905042057/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
Deprecated @ file:///opt/conda/conda-bld/deprecated_1659726428456/work
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1673645807193/work
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
esda @ file:///home/conda/feedstock_root/build_artifacts/esda_1660931045600/work
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1671811474537/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1663619548554/work/dist
Fiona @ file:///croot/fiona_1678226032672/work
flit_core @ file:///home/conda/feedstock_root/build_artifacts/flit-core_1667734568827/work/source/flit_core
folium @ file:///home/conda/feedstock_root/build_artifacts/folium_1670956290671/work
fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1666827164138/work
frozenlist @ file:///home/conda/feedstock_root/build_artifacts/frozenlist_1667935428519/work
fsspec @ file:///croot/fsspec_1682525977151/work
future @ file:///home/conda/feedstock_root/build_artifacts/future_1673596611778/work
GDAL @ file:///home/conda/feedstock_root/build_artifacts/gdal-split_1673844024878/work/build/swig/python
geographiclib @ file:///home/conda/feedstock_root/build_artifacts/geographiclib_1624386157733/work
geojson @ file:///home/conda/feedstock_root/build_artifacts/geojson_1676562884917/work
geopandas @ file:///home/conda/feedstock_root/build_artifacts/geopandas_1670698600430/work
geopy @ file:///home/conda/feedstock_root/build_artifacts/geopy_1668350868373/work
gitdb @ file:///home/conda/feedstock_root/build_artifacts/gitdb_1669279893622/work
GitPython @ file:///home/conda/feedstock_root/build_artifacts/gitpython_1672338156505/work
HeapDict==1.0.1
holoviews @ file:///croot/holoviews_1690477566927/work
hvplot @ file:///croot/hvplot_1685998166135/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1672612343532/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1672681417544/work
ipykernel @ file:///croot/ipykernel_1691121631942/work
ipython @ file:///croot/ipython_1691532092695/work
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1671720089366/work
isodate @ file:///home/conda/feedstock_root/build_artifacts/isodate_1639582763789/work
itsdangerous @ file:///home/conda/feedstock_root/build_artifacts/itsdangerous_1648147185463/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1663332044897/work
json5 @ file:///tmp/build/80754af9/json5_1624432770122/work
jsonlines==1.2.0
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1669810440410/work
jupyter @ file:///home/conda/feedstock_root/build_artifacts/jupyter_1670249604934/work
jupyter-console @ file:///croot/jupyter_console_1679999630278/work
jupyter-events @ file:///home/conda/feedstock_root/build_artifacts/jupyter_events_1673559782596/work
jupyter-server-mathjax @ file:///home/conda/feedstock_root/build_artifacts/jupyter-server-mathjax_1672324512570/work
jupyter-ydoc @ file:///croot/jupyter_ydoc_1683747223142/work
jupyter_client @ file:///croot/jupyter_client_1680171862562/work
jupyter_core @ file:///croot/jupyter_core_1679906564508/work
jupyter_server @ file:///croot/jupyter_server_1686059464471/work
jupyter_server_fileid @ file:///croot/jupyter_server_fileid_1684273577568/work
jupyter_server_terminals @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_terminals_1673491454549/work
jupyter_server_ydoc @ file:///croot/jupyter_server_ydoc_1686767404829/work
jupyterlab @ file:///croot/jupyterlab_1686179668131/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1649936611996/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1671722028097/work
jupyterlab_git @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab-git_1691684056267/work
jupyterlab_server @ file:///croot/jupyterlab_server_1680792501448/work
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1666805784128/work
libpysal @ file:///home/conda/feedstock_root/build_artifacts/libpysal_1646347632001/work
llvmlite==0.39.1
locket @ file:///home/conda/feedstock_root/build_artifacts/locket_1650660393415/work
loguru @ file:///home/conda/feedstock_root/build_artifacts/loguru_1666819027341/work
lxml @ file:///home/conda/feedstock_root/build_artifacts/lxml_1671013460024/work
lz4 @ file:///croot/lz4_1686057876374/work
mapclassify @ file:///home/conda/feedstock_root/build_artifacts/mapclassify_1673861555770/work
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1657921053229/work
markdown-it-py @ file:///croot/markdown-it-py_1684279902645/work
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1674135804847/work
matplotlib @ file:///croot/matplotlib-suite_1679593461707/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mdurl @ file:///opt/conda/conda-bld/mdurl_1659716024347/work
mercantile @ file:///home/conda/feedstock_root/build_artifacts/mercantile_1619028378680/work
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1657892024508/work
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1666755171270/work
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1672339396340/work
munch==2.5.0
munkres==1.1.4
nbclassic @ file:///croot/nbclassic_1681756170010/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1669795076334/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert-meta_1673893169158/work
nbdime @ file:///home/conda/feedstock_root/build_artifacts/nbdime_1682876851950/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1673560067442/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
netCDF4 @ file:///home/conda/feedstock_root/build_artifacts/netcdf4_1668678836987/work
networkx @ file:///croot/networkx_1690561992265/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1667565639349/work
notebook_shim @ file:///home/conda/feedstock_root/build_artifacts/notebook-shim_1667478401171/work
numexpr @ file:///croot/numexpr_1683221822650/work
numpy==1.23.5
OWSLib @ file:///home/conda/feedstock_root/build_artifacts/owslib_1661798335503/work
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1673482170163/work
pandas @ file:///croot/pandas_1692289311655/work
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
panel @ file:///croot/panel_1676379587510/work
param @ file:///croot/param_1684915322283/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1660316728562/work
patsy @ file:///home/conda/feedstock_root/build_artifacts/patsy_1665356157073/work
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1672675315618/work
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
platformdirs @ file:///croot/platformdirs_1692205439124/work
plotly @ file:///home/conda/feedstock_root/build_artifacts/plotly_1673709489168/work
ply==3.11
pooch @ file:///home/conda/feedstock_root/build_artifacts/pooch_1643032624649/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1665692535292/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1670414775770/work
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1667885909637/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
py3dep @ file:///home/conda/feedstock_root/build_artifacts/py3dep_1683516422484/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pyct==0.4.6
pygeoogc @ file:///home/conda/feedstock_root/build_artifacts/pygeoogc_1683511556642/work
pygeos @ file:///home/conda/feedstock_root/build_artifacts/pygeos_1670848341872/work
pygeoutils @ file:///home/conda/feedstock_root/build_artifacts/pygeoutils_1683511567989/work
Pygments @ file:///croot/pygments_1684279966437/work
pyOpenSSL @ file:///croot/pyopenssl_1690223430423/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
pyproj @ file:///home/conda/feedstock_root/build_artifacts/pyproj_1670929452369/work
PyQt5==5.15.7
PyQt5-sip==12.11.0
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1672681476680/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
pystac @ file:///home/conda/feedstock_root/build_artifacts/pystac_1691712014739/work
pystac-client @ file:///home/conda/feedstock_root/build_artifacts/pystac-client_1687791816275/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-forge @ file:///home/conda/feedstock_root/build_artifacts/python-forge_1619215951105/work
python-json-logger @ file:///croot/python-json-logger_1683823803357/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1673864280276/work
pyviz-comms @ file:///croot/pyviz_comms_1685030693726/work
PyYAML @ file:///home/conda/feedstock_root/build_artifacts/pyyaml_1666772387118/work
pyzmq @ file:///croot/pyzmq_1686601365461/work
qtconsole @ file:///croot/qtconsole_1681394213385/work
QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1667873092748/work
quantecon==0.6.0
rasterio @ file:///home/conda/feedstock_root/build_artifacts/rasterio_1668654942870/work
redis @ file:///opt/conda/conda-bld/redis-py_1664990640096/work
requests @ file:///croot/requests_1690400202158/work
requests-cache @ file:///home/conda/feedstock_root/build_artifacts/requests-cache_1673645254896/work
rfc3339-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3339-validator_1638811747357/work
rfc3986-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3986-validator_1598024191506/work
rioxarray @ file:///home/conda/feedstock_root/build_artifacts/rioxarray_1692046920781/work
Rtree @ file:///home/conda/feedstock_root/build_artifacts/rtree_1666813326661/work
scikit-learn @ file:///croot/scikit-learn_1690978916802/work
scipy @ file:///croot/scipy_1691606680890/work/dist/scipy-1.11.1-cp39-cp39-linux_x86_64.whl#sha256=f14d126714b348fb60b767a5251c0f64b5d5cb690dbedcd4f74daa8b9d3e3dad
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1672497695270/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
shapely @ file:///home/conda/feedstock_root/build_artifacts/shapely_1670855156806/work
sip @ file:///home/conda/feedstock_root/build_artifacts/sip_1669039925930/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
smmap @ file:///home/conda/feedstock_root/build_artifacts/smmap_1611376390914/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/work
snuggs==1.4.7
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1621217038088/work
soupsieve @ file:///croot/soupsieve_1680518478486/work
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
stackstac @ file:///home/conda/feedstock_root/build_artifacts/stackstac_1687780024967/work
statsmodels @ file:///croot/statsmodels_1689937266057/work
suds-jurko @ file:///home/conda/feedstock_root/build_artifacts/suds-jurko_1610146492473/work
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1616261298899/work
tenacity @ file:///croot/tenacity_1682972284834/work
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1670253674810/work
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1643647933166/work
tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1666100256010/work
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1604308577558/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
tornado @ file:///croot/tornado_1690848263220/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1662214488106/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1673359992537/work
typing_extensions @ file:///croot/typing_extensions_1690297465030/work
tzdata @ file:///croot/python-tzdata_1690578112552/work
ujson @ file:///home/conda/feedstock_root/build_artifacts/ujson_1666837350618/work
ulmo @ file:///home/conda/feedstock_root/build_artifacts/ulmo_1630698889861/work
unicodedata2 @ file:///home/conda/feedstock_root/build_artifacts/unicodedata2_1667239485250/work
url-normalize @ file:///home/conda/feedstock_root/build_artifacts/url-normalize_1619201332663/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1673452138552/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1667568040382/work
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1672066693230/work
wrapt @ file:///tmp/abs_c335821b-6e43-4504-9816-b1a52d3d3e1eel6uae8l/croots/recipe/wrapt_1657814400492/work
xarray @ file:///croot/xarray_1689041471350/work
xyzservices @ file:///croot/xyzservices_1675159059961/work
y-py @ file:///croot/y-py_1683555143488/work
yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1672340978046/work
ypy-websocket @ file:///croot/ypy-websocket_1684171737040/work
zict @ file:///home/conda/feedstock_root/build_artifacts/zict_1651156074437/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1669453021653/work
